services:
  app: # This is the service name
    build: .
    container_name: fastapi-server # Change the container name to whatever you want
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
      - 5678:5678 # This is use for debugging python using debugpy
    volumes:
      - .:/app # This is the WORKDIR in Dockerfile